### ISSUE TITLE
Chaos on Deponia sound lag, not playing movies and not saving issues

### ISSUE THREAD

**Issue by GabiAle97** [skyline-emu/skyline#1047]
Hi! Been testing the Deponia Saga (i feel like i'm bothering you so much with this 😅) and had that issues with Chaos, wich is the only one working ingame. All other 3 games are reaching the tittle screen (no reaction, like it doesn't obbey the control) after skipping the intro cutscenes (wich aren't playing in ANY of these games). In Chaos, some character animations don't work properly (Rufus's sprite is standing while another Rufus's sprite takes a hamer and "kill" a bird), so I asumme that there are some more glitches like this after. Is there a posibility that this bugs gets corrected in the near future?

**Comment by PixelyIon** [comment]
Hey there, there's a lot of game issues to be expected at the moment for anything we don't explicitly claim is supported. If something but you want it to be, go ahead an open a game request discussion or upvote an existing one. 

Bugs like this will likely be fixed as a result of fixing another (more popular) game generally but in some cases it isn't in which case you'll have to wait for the Skyline team to get to it and that only happens if it's on our radar which it generally only is when there's a highly upvoted game request about it.
