### ISSUE TITLE
The joystick on the left joy-con does not work correctly with the emulator

### ISSUE THREAD

**Issue by MalseMakreel** [skyline-emu/skyline#1057]
The joystick on the left joy-con does not work. It only registered the click of the stick, but it didn't register the direction input.  (The left joy-con registers the joystick button and the direction input correctly)

**Comment by PixelyIon** [comment]
Are you talking about the emulated JoyCon or a real JoyCons that you're using as the controller for Skyline? If it's the latter then it's an issue with the kernel driver for the JoyCons, Skyline just picks up inputs from Android if Skyline is missing them from the Right JoyCon then it's on Android not passing that through to us rather than on us.

**Comment by MalseMakreel** [comment]
I am sorry for not being clear. I meant a physical joy-con.. so does that means that Android doesn't pass it to Skyline correctly?

**Comment by PixelyIon** [comment]
Correct, this is not really on us but there is something we may be able to do about it in the future with a custom HID driver but not anytime soon. We're too focused on other parts of the emulator.

**Comment by MalseMakreel** [comment]
I can well imagine that this is a problem for later.  Still, I'm glad to hear that you might have a solution for it.  Thanks for your response, and good luck with the emulator in the future!  PS: a completely different point, but if you are possibly looking for a Dutch translator, I could provide you with my service

**Comment by bylaws** [comment]
This is a bug on our side
