### ISSUE TITLE
Option to adjust resolution and graphics 

### ISSUE THREAD

**Issue by leopeo-star** [skyline-emu/skyline#1058]
I know the team is very busy pushing the emulator to make it work on more games and optimising it but it would be really helpful to run games with better fps and emulation speed if we had the option to turn the graphics and resolution down a bit would be more useful before more big games comes into play

**Comment by PixelyIon** [comment]
We can't really modify the graphics pipeline of games in a way that is generic due to how complex modern GPUs and games are, that'll need to be handled on a per-game mod basis which we will support at some point. We will add support for resolution scaling later on but it's not a priority at the moment and is also best done via mods realistically.
