### ISSUE TITLE
Get more information about the roms

### ISSUE THREAD

**Issue by francexecomb** [skyline-emu/skyline#1063]
Would like to get for each rom file base information like the release date of the game, title ID, go to save folder, which prod.key version is required, show which prod.key version is installed.

**Comment by PixelyIon** [comment]
ROMs don't have information such as release date in a fixed format as far as I know. We will expose title ID among other available metadata with title-meta (PTMD), key data will not be provided since it is rather pointless for the vast majority of users. I will add that these requests are better done as GitHub Discussions feature requests rather than issues.
