### ISSUE TITLE
FPS with High Screen Hz

### ISSUE THREAD

**Issue by Jaludex** [skyline-emu/skyline#1066]
It looks like the Frames per seconds are limited to the screen Hz, so if I activate 120hz, the game runs at 120fps (runs twice as fast). It's just me?

Example video: https://user-images.githubusercontent.com/53153684/164592583-986c73cb-430f-45c6-ba5f-94f636e45e9f.mp4

**Comment by PixelyIon** [comment]
This issue seems to be the same as https://github.com/skyline-emu/skyline/issues/415. It's an OS-level bug which we can't fix on our end, you'll have to manually lower the refresh rate or use a utility which can automatically do so for you. I'll be closing this issue as we have no other issue resolutions at the moment.

**Comment by Jariel87** [comment]
It depends the game, ex sonic mania it triple the fps, but games like hollow or celeste dont
