### ISSUE TITLE
Bind volume buttons as controller input

### ISSUE THREAD

**Issue by MableOvO** [skyline-emu/skyline#1190]
when binding an input to something on the actual phone, such as the volume slider it doesnt actually disable the  button's actual function. would be neat if it did though

**Comment by PixelyIon** [comment]
We'll look into this at some point.

**Comment by KikiManjaro** [comment]
I think this problem is related to the device or maybe Android version.
I can't reproduce this problem on a Xiaomi Mi Pad 5 (Android 11), while adding Volume Up as the A button for exemple, the volume is never increase while in game and pressing the button.

@MableOvO can you provide more information about your device and the Android version you're using ? Also, is this problem still present on your device ?

**Comment by MableOvO** [comment]
> I think this problem is related to the device or maybe Android version.
> I can't reproduce this problem on a Xiaomi Mi Pad 5 (Android 11), while adding Volume Up as the A button for exemple, the volume is never increase while in game and pressing the button.
> 
> @MableOvO can you provide more information about your device and the Android version you're using ? Also, is this problem still present on your device ?

for more info: Im using an S21+ with its stock android 11 and after skylines most recent updates this behavior is still present

**Comment by MableOvO** [comment]
> > I think this problem is related to the device or maybe Android version.
> > I can't reproduce this problem on a Xiaomi Mi Pad 5 (Android 11), while adding Volume Up as the A button for exemple, the volume is never increase while in game and pressing the button.
> > 
> > @MableOvO can you provide more information about your device and the Android version you're using ? Also, is this problem still present on your device ?
> 
> for more info: Im using an S21+ with its stock android 11 and after skylines most recent updates this behavior is still present 
> 

ACTUALLY correction: *android 12
