### ISSUE TITLE
Implement Adrenotools UI

### ISSUE THREAD

**Issue by Sovietfowl** [skyline-emu/skyline#1587]
Implement the UI for Adrenotools to provide a way for users with Adreno GPU phones to choose their own drivers.

**Comment by smoothedu** [comment]
Tera algum suport para gpu mali futuramente?

**Comment by PixelyIon** [comment]
We will not be adding Mali support due to the lack of a stable kernel ABI, it just isn't possible to do so unless ARM changes how Mali drivers work. 

The only other vendors there might be a chance at it working for is AMD but there's no devices aside from the Exynos 2200 with the S22, we wouldn't have the ability to get a newer drivers.

Additionally, this is an English only forum as it'd be really hard to moderate if there's multiple languages.

**Comment by Sovietfowl** [comment]
Merged on the latest build.
