### ISSUE TITLE
Sign the damned apks again so they can be updated, or I'll do it myself.

### ISSUE THREAD

**Issue by AlexS2412** [skyline-emu/skyline#1627]
this shouldn't even have to exist @PixelyIon... just sign the github releases again so they can be updated if users CHOOSE to, as this is the point of releasing builds at all.

**Comment by MCredstoner2004** [comment]
The latest few APKs aren't signed because they come from the PR I'm working on, and GitHub Actions doesn't really like it when other repos get access to the secrets, if you want to update with the changes I'm working on without having to backup your data, uninstall, install the unsigned APK, and then copy your data back then you're free to wait until the changes are merged

**Comment by PixelyIon** [comment]
Additionally, being rude and entitled will get you nowhere. This is not acceptable behavior and you have been temporarily blocked as a result.
