### ISSUE TITLE
Are you planning to create a Patreon page?

### ISSUE THREAD

**Issue by AyderProgramic** [skyline-emu/skyline#174]

**Comment by KingHackerMan** [comment]
> 

I don't think they plan on opening a patreon in the immediate future, thought they have talked about incorporating optional ads in the application

**Comment by davyson123** [comment]
Oi amigão boa tarde. Amigo vc pode implantar a gpu do apk do egg ns para o skyline ?

**Comment by AyderProgramic** [comment]
what is this language?

**Comment by AyderProgramic** [comment]
Write in English!
If you don't know how to write in English use Google translator

**Comment by NKS1608** [comment]
> Oi amigão boa tarde. Amigo vc pode implantar a gpu do apk do egg ns para o skyline ?

I don't think it's possible, that would be using stolen code, and egg ns already uses yuzu's stolen code

**Comment by davyson123** [comment]
but the gpu code is already coming out?

**Comment by NKS1608** [comment]
> but the gpu code is already coming out?

they are implementing but I'm not part of the team so I'm not sure of the progress

**Comment by PixelyIon** [comment]
I think @KingHackerMan answered this sufficiently, we don't plan on it at the moment but we might do one in the future depending on how things go. I'll be locking this thread now due to the amount of off-topic comments, GPU is being worked on at the moment but we have no fixed ETA on when it'll be out.
