### ISSUE TITLE
Buen avance 

### ISSUE THREAD

**Issue by MONDONGO07** [skyline-emu/skyline#1781]
La verdad hace tiempo vengo viendo skyline y ver como mejora es todo una joya muchas gracias por mejorar el emulador de apoco son unos genios tendrá fallas si pero que emulador no tiene fallas además es un gran avance ver qué juegos como hollow knight antes andaba a 20 o 30 fps ahora anda a 60 fps es un gran avance de apoco muchas gracias espero y sigan adelante muchas gracias

**Comment by Sovietfowl** [comment]
While we do appreciate the kind words this forum is meant to make issues about Skyline and not for congratulating the devs as this would clutter up the repo, also try to use English next time as this is an English only forum. But otherwise we do appreciate this kind words and thank you for your support.
