### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by mauricio-ricalde** [skyline-emu/skyline#1834]
I know Skyline is still a new project, and this may be a little too much to ask, but macOS desperately needs a Switch emulator. Yuzu and Ryujinx doesn't work, but Skyline represents a ray of hope for us Mac users. You see, PCSX2, the PS2 emulator, has its own Mac version, but support has been a pain and it isn't as good as the Apple Silicon version of AetherSX2, a PS2 emulator for Android. Of course, given the similarities in architecture between Apple Silicon Macs and mobile devices, porting AetherSX2 to the Mac was a relatively simple process. The catch is that it only works on Apple Silicon Macs, but since that's where the future of the platform is headed, I think it's a fair sacrifice and an investing on that future, even if Intel-based Macs aren't supported.

Now, I'm not an expert, but I've read a bit on Yuzu's and Ryujinx's forums, and I know that the current version of MoltenVK doesn't support some of the features needed for emulating Switch's graphics on Vulkan. That's a limitation of Metal, but that could change with the release of Metal 3, as part of macOS Ventura. So I'm guessing it's just a matter of time for MoltenVK to catch up and support the necessary features to emulate the Switch. In the meantime, I ask you to consider porting Skyline to the Mac, please. Even if it's considered a small side project like the Mac version of AetherSX2 (which is totally understandable), it'll be greatly welcomed.

**Comment by NotintoCode** [comment]
Hey I'm not into code but i just joined here to tell this prick that how hard it is for us Andriod users who suffer from games recently, and you just here to comment to suggest that skyline will be add on mac, if you can afford a pricking mac why not buy a pc or laptop prick! We Andriod users have a lot of problem games from pc not imported to andriod and I'm one who doesn't have a money to buy PC or Laptop because you might say "Why not Buy PC" Prick we suffered enough!! Long Enough!! We need a breather this app is a live saver! Don't listen to that prick! I needed that glad i get that off my chest because i've been suffering finding good games nowadays this is the biggest news i've got.

**Comment by Swizzlefowl** [comment]
@NotintoCode take it as a warning but don't be inflammatory towards people, also Mac support is far in the future as the devs are currently focusing on Android.

**Comment by PixelyIon** [comment]
A lot of what's wrong with a potential iOS port, discussed at #387 also applies to this issue. The lack of Vulkan makes it incredibly annoying, we'd have to do a fair bit of workarounds for MoltenVk to work correctly and this just isn't on the roadmap at the moment due to the amount of effort involved.

**Comment by NotintoCode** [comment]
Mark thanks! You really have a time and energy to help us andriod users, you're the guy that i didn't become if I'd really know coding i do help. If i get a second chance in life i'll become a coder, this people who make games, emulator etc in PC and LT i don't get why they mostly stop at pc only it's maybe because phone user have a lot of piracy lol, but yeah maybe that's the case.

**Comment by PixelyIon** [comment]
Since we have no current plans for this and [Ryujinx](https://ryujinx.org/) has done a fantastic Mac OS port. I'm going to go ahead and close this issue.
