### ISSUE TITLE
Google TV 12 (android 12) file access issues

### ISSUE THREAD

**Issue by SzymonZy** [skyline-emu/skyline#2064]
On google tv 12 (android) You can't chose file locations in settings. Due to changes in android API android pops up with notificatuon that there is no google files installed. Is there any workaround? Tested on latest public build of Skyline.

**Comment by Mononono87** [comment]
May be a Google tv issue? Not sure,I was looking it up and I can't even find a spec sheet for jt

**Comment by SzymonZy** [comment]
https://forum.xda-developers.com/t/google-tv-file-manager-problem.4478099/
The same hits skyline and citra. So definitelly this is android 12 change in storage subsystem.

**Comment by Shaggy013** [comment]
Ah nice i got the same question on the raxda forum 
https://forum.radxa.com/t/rom-rock-5b-android-12-1-rkr10-googletv/13208/92?u=thc013

it seems that there is no native filemanager from what i understand . 

so i see t it more like this 

the youtube video is from a box with default rk box wich is more a tablet version with a rk launcher or the leanback launcher from lineage and the tablet has the native filemanager 

the googletv cfw is more leaning to the atv version of android with the packages from a adt3 gtv img and because the native filemanager is not in atv builds it cannot find it

**Comment by SzymonZy** [comment]
This is obvious, but does it mean that on android tv 12 Skyline (among
other emus) will not be available?

sob., 10 gru 2022, 13:45 użytkownik Shaggy013 ***@***.***>
napisał:

**Comment by Swizzlefowl** [comment]
This is not really an Skyline issue so I will be closing this.

**Comment by Shaggy013** [comment]
from the cfw view i can understand it is not the issue of skyline 

so that is why i asked if it runs on a Android 12 GTV based device so minus bad cfw ;) ?  then it is still not realy a issue just not GTV compatible
