### ISSUE TITLE
Make a iOS Version of Skyline!

### ISSUE THREAD

**Issue by Jadon67** [skyline-emu/skyline#2108]
Hi. I heard that your app is a Nintendo switch emulator. But it’s only for android:(
Can you make a iOS version of Skyline please. Don’t put it in the App Store because apple  will take it down.
Instead, do this.
IPA:non-jailbreak
DEB:Jailbreak
IPA: sideload with Mac or pc
DEB: Use slieo or Saily or Filza
Anyways, THIS IS NOT A ISSUE!!
Anyways, bye

**Comment by Jadon67** [comment]
Also, use Xcode

**Comment by iniMerchant64** [comment]
Im afraid that will not happen. Current devs are not interested in working on an IOS port. The only chance this could be a thing is if some other developer decides to pick it up and port it over

**Comment by AbandonedCart** [comment]
> Im afraid that will not happen. Current devs are not interested in working on an IOS port. The only chance this could be a thing is if some other developer decides to pick it up and port it over

That's not entirely true. They've actually expressed that it's due to the number of workarounds required being too much at the present time. It's a bit unfair to imply it's because they don't feel like it. On top of that, it's typically been asked as a list of demands for how they include support, but not from anyone with the intention of being involved in the process.
