### ISSUE TITLE
Add patching for games

### ISSUE THREAD

**Issue by BIGD15** [skyline-emu/skyline#214]
To patch games or update versions or adding dlc's

**Comment by PixelyIon** [comment]
Hey, we'll implement all of this in time and we would generally keep an issue open till it would be addressed but the scope of this issue is a bit too large. We'll create and manage more atomic issues like "Update Support", "DLC Support", "ExeFS Patching Support" and "RomFS Patching Support" later on. At the time being I'll be closing this issue in favor of those later.
