### ISSUE TITLE
[CXX1405] error when building with cmake using CMakeLists.txt: Build command failed.

### ISSUE THREAD

**Issue by vincecarterhu** [skyline-emu/skyline#2189]
CMake Error at CMakeLists.txt:27 (add_subdirectory):
  add_subdirectory given source "libraries/llvm/libcxx" which is not an
  existing directory.

**Comment by cylee0909** [comment]
try 'git submodule update --recursive'

**Comment by AbandonedCart** [comment]
If you updated your submodules beyond the specific commits provided by this repository, there is an issue where one of them becomes incompatible with the configuration in the repository. Your best bet would be to undo any local updates to the submodule hashes and then try it again. I believe "fmt" had one such issue.

**Comment by Gabryxx7** [comment]
Just chiming in as I had a similar issue: In my case the problem was that the library used was the one from homebrew (macOS). What I ended up doing is removing FMT from the system libraries in `target_link_libraries_system` as well as deleting `SYSTEM` from  `include_directories(SYSTEM "libraries/mbedtls/include")`.

Have a look if your setup is looking at the right folders. In my case, it was including files from the homebrew installed library instead of the one cloned recursively with the repo

**Comment by AbandonedCart** [comment]
Homebrew is a gift and a curse for that exact reason. I was running against Ubuntu, which is likely going to be similar to the end result of using a Homebrew binary. It may not hurt to make the change across the board.
