### ISSUE TITLE
Black screen while running Pokemon games

### ISSUE THREAD

**Issue by SilentLover48** [skyline-emu/skyline#250]
Kindly update the graphics in games as soon as possible. Unable to play pokemon games. If you can fix graphics in your emulator, skyline becomes the first and only emulator to run pokemon games on android without controllers. So fix this ASAP

**Comment by PixelyIon** [comment]
We're working on it, this issue is redundant as stated in #168.

**Comment by Techguy791** [comment]
> Kindly update the graphics in games as soon as possible.

You do realize it's not as simple as writing a few lines of code and compiling, right? Building an emulator, especially for Android, is no easy task. Lots of researching, lots of reverse-engineering, and _lots and lots_ of programming goes into it. That's the reason PS4 emulation only recently got somewhere, it took _years_ to figure it all out. Inversely, that's why Dolphin works so well and has such a high compatibility: it's been in development since 2003. Also, this emulator is still in its early stages, so graphics aren't likely going to be implemented for awhile.
This isn't meant to be rude or anything by the way. I'm only trying to give an explanation, and willing to edit this post if it sounds condescending at all.
