### ISSUE TITLE
anyone know why i cant play undertale?

### ISSUE THREAD

**Issue by Boneyuwu** [skyline-emu/skyline#296]
It does not have graphics, it is pixels

**Comment by RazyRabbit** [comment]
The emulator is not ready to play real games, just a couple of test ROMs

**Comment by RazyRabbit** [comment]
It is neither in a pre alpha stage

**Comment by RazyRabbit** [comment]
> It does not have graphics, it is pixels

[](https://github.com/skyline-emu/skyline/issues/168#issue-874908511)

**Comment by dineshkhadka** [comment]
2D graphics is still graphics.

**Comment by RazyRabbit** [comment]
> 2D graphics is still graphics.

The ""emulator"" doesn't currently supports graphics in general.

**Comment by PixelyIon** [comment]
As reiterated above, "pixels" are graphics and they aren't supported at the moment outside of some very specific test games. Initial support for commercial games with graphics is in the near future but the scope of games will be limited at first and Undertale in particular needs attention due to GameMaker depending on some edge case behavior on the GPU and it won't be done until we get the core base of games we're interested in supported well enough.

**Comment by UnknownAMD** [comment]
imagine not knowing what the word "graphics" means lol

**Comment by edisionnano** [comment]
Undertale being a gamemaker game has an android port btw, you dont need an emulator

**Comment by riperiperi** [comment]
Undertale doesn't have an official android port, and as far as I'm aware there are issues with it right now. Playing your own switch dump is still preferable.

**Comment by tuleo1** [comment]
yes and no, I've played the the port many times myself, it's pretty good and it really doesn't have any issues, it's fine with no issues and I don't think it's really any different than playing on the switch emulator anyways, both give the same experience

**Comment by MCredstoner2004** [comment]
It's not an official port but since it's a gamemaker game, you can definitely run it on android using the PC version's files with some minor tweaking, not sure if you can do the same thing based on the switch dump, which has some extra content, there's a way to play the switch version on PC as well
