### ISSUE TITLE
Make app full screen plz

### ISSUE THREAD

**Issue by BIGD15** [skyline-emu/skyline#303]
I have poco x3 pro and there's a black line where camera been

+ Screen rotation

When i playing emu is rotates the screen by the one side and i can't rotate it to another

**Comment by PixelyIon** [comment]
Dynamic screen rotation will likely never be supported due to how Android Activities works but we will add an option in Settings to set it beforehand. Support for matching the 16:9 aspect ratio of the Switch and filling the space with outlines will also be added but these are individual issues and shouldn't be put in a single issue, I'll create TODO items for them and turn them into issues when they're done. I'll be closing this, please ask in our Discord before creating any issues concerning feature requests.
