### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by Infinityfox47** [skyline-emu/skyline#339]

**Comment by riperiperi** [comment]
++

**Comment by PixelyIon** [comment]
FPS?

**Comment by NotAWeeb69** [comment]
no delete

**Comment by MACEDONIAz** [comment]
Purge from existence

**Comment by lynxnb** [comment]
Yes we'll add

**Comment by BIGD15** [comment]
And fix

**Comment by MCredstoner2004** [comment]
### **_Add_**

**Comment by Allatel** [comment]
ADDMONEY

**Comment by BIGD15** [comment]
Did you added Mark?

**Comment by PixelyIon** [comment]
We've thought about this issue a lot in the Skyline team, we've come to the conclusion that "Add" can mean one of two things:
* Adding a feature
* Mathematical Addition

We don't accept feature requests on GitHub issues so assuming the author does know that, it can only mean that this involves addition which uhm.. 
I suppose we never specified we wouldn't accept issues concerning arithmetic and addition is a rather simple operation, yet, what might seem simple isn't because addition requires two terms but none are specified.. this is where we brought in the experts.

On further investigation, we determined that the involved terms are 339 and 47. The answer of `339 + 47` is at the very least 340, I'd wager even 341. You might be perplexed by my mathematical skill after seeing my expert deductions, I don't like to show off but it's true, I'm very good at math. I can even count till the number 7, a feat achieved by few.

![337 + 47](https://user-images.githubusercontent.com/17637537/149903523-0c921208-e40d-4f82-bdbc-d0dddb4d021c.png)

Now, we're left to wonder what Mr. Fox made us perform this addition for. This is where most people would give up (even experts), yet, Skyline Team has cracked the code. There was a third conclusion all along:
* Add 386$ to [Skyline's Patreon](https://forms.gle/bsqt34q95y9FLbKA7)

**Comment by Sebaspro98** [comment]
😃

**Comment by hugo6831** [comment]
Hi
