### ISSUE TITLE
Crash on launch with Adreno Tools in FTX1 builds

### ISSUE THREAD

**Issue by zdyyy95** [skyline-emu/skyline#403]
Can't open app after "Add support for turnip and driver file redirection via libadrenotools" (Google translate)

**Comment by PixelyIon** [comment]
There were bugs in that build which have to the best of my knowledge, been fixed. Try the [latest `ftx1` build](https://github.com/skyline-emu/skyline/actions/runs/1883863616) and report back if that has the issue too.

**Comment by zdyyy95** [comment]
The latest ftx1 build doesn't open
Qualcomm Snapdragon 665

**Comment by PixelyIon** [comment]
Can you come to the [Discord server](https://discord.gg/XnbXNQM)? it's going to be hard to debug over GitHub issues. I should add that the SD665 is below the minimum requirements and at the very most will run basic 2D games if even that much. I will be closing the issue due to how non-descript it is, you'll need to join the Discord for further debugging.

**Comment by zdyyy95** [comment]
I have the same problem with the aethersx2 ADRENO GPU dedicated version, I think the Turnip driver is causing the crash. Because on older versions there was no problem (Google translate)
![Screenshot_20220227_092241](https://user-images.githubusercontent.com/45879085/155864585-61fc7fd4-9999-4c23-8a4f-cae3e39c55fe.jpg)

**Comment by Techguy791** [comment]
I have the same issue, even with the latest FTX1
