### ISSUE TITLE
Screen rotating issue android 12

### ISSUE THREAD

**Issue by acrid404** [skyline-emu/skyline#441]
While i run game with skyline emu i get rotating 

https://user-images.githubusercontent.com/75588714/157416011-55da426f-0661-4521-ba2e-694287c274e2.mp4

issue this bug started happening when i updated my miui to 13(android 12) before andoid was 11

**Comment by ShadowBlakc** [comment]
Damn Skyline,
Since it seems that skyline will only be for high-end cell phones,
I feel that it is one more damn disappointment, ruined thing, damn life,

>:'€
Hopefully and always yes if a damn nuclear war happens so that everything goes to shit once and for all,
fucking world... 
I just wanted to play the pokemon games to calm my fucking rage for this fucking world........

**Comment by NotAWeeb69** [comment]
Not at all. Weve seen sd662/665 users launching sonic mania last the fps cap. 
Besides, the official minimum for the past 1y+ was sd845 which believe it or not isnt high end at all

**Comment by PixelyIon** [comment]
@ShadowBlakc If you make more unrelated comments under random issues then you will be banned from the repository.

**Comment by PixelyIon** [comment]
@acrid404 I think this is probably just a MIUI issue (which we likely cannot fix) and not an Android issue but I'll ping @lynxnb in any case, he can close the issue if it does seem to be a MIUI-specific issue.

**Comment by ddmdareal** [comment]
Same thing on OneUI 4.0 Android 12, but it also happens on the main screen

**Comment by lynxnb** [comment]
Can any of you two guys report this issue on the skyline discord so that we can confirm this being an issue with OEMs?
