### ISSUE TITLE
Oculus quest 1 crash

### ISSUE THREAD

**Issue by terabytez** [skyline-emu/skyline#479]
Hi, skyline in Meta quest 1 crashes, i know its not expected to work on oculus system, but if u can check why dont work i appreciated it c:

**Comment by NotAWeeb69** [comment]
Send log. Its the button next to settings

**Comment by terabytez** [comment]
The app crash on startup, doesnt open.

**Comment by terabytez** [comment]
I guess the permission to use storage is diferent to a normal Android device

**Comment by NotAWeeb69** [comment]
I see, in that case i guess wed need a logcat to see why it crashes. Would you be able to provide one?

**Comment by sauradipdebnath** [comment]
Don't open issues like that

**Comment by sauradipdebnath** [comment]
Don't open issues like that

**Comment by sauradipdebnath** [comment]
Refer to #372

**Comment by sauradipdebnath** [comment]
You Ignored

**Comment by NotAWeeb69** [comment]
> You Ignored
Can you stop? We dont scold people here for opening issues which state an actual issue. issue #372 states that skyline is in pre alpha. Since oculus is a snapdragon device it should be compatible

**Comment by PixelyIon** [comment]
@terabytez This is a known issue, it's due to the Oculus Quest 1 and 2 being unable to handle the [OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE) intent. We can't really do anything about this, they need to fix their implementation of SAF and I'll be closing this issue as a result.
