### ISSUE TITLE
Add a ROADMAP.md

### ISSUE THREAD

**Issue by mguinhos** [skyline-emu/skyline#496]
It will helpful to have information about which features was already implemented, or which are still in development

**Comment by PixelyIon** [comment]
As discussed on Discord, a `ROADMAP.md` is a poor way to handle this and the alternative of a GitHub Issue is as well. We may consider other forms of a roadmap in the form of blog posts at a later date but at the moment due to rapid development, it's quite hard to index everything and we would need to constantly update the roadmap which we have attempted in the past with a GitHub Project but it's quite the hassle. As a result, I'll be closing this issue.
