### ISSUE TITLE
Status bar not hiding in EmulationActivity

### ISSUE THREAD

**Issue by josesilveiraa** [skyline-emu/skyline#981]
Android version: 11R
ROM: ArrowOS
Device: Poco X3 Pro

I see there's a line setting the FLAG_FULLSCREEN, but it doesn't work, at least in this ROM. In other ROMS it hides with no issues.
https://github.com/skyline-emu/skyline/blob/882b9393356572611c0951c49f85e07bce520a6c/app/src/main/java/emu/skyline/EmulationActivity.kt#L303

**Comment by PixelyIon** [comment]
@lynxnb has effectively tried every possible way to make it go away and if it doesn't work at this point, it's an issue with the ROM and not really with Skyline. You'll have to contact the ROM developers rather than us.

**Comment by PixelyIon** [comment]
If you can figure out what flags causes it to work then we're ready to accept any commits but otherwise as far as we can tell with using the only non-deprecated APIs to hide the status bar insets, they don't work and it's an issue with your ROM's Android framework implementation not with Skyline as an API-user.
